version: "3.9"
services:
  database:
    image: postgres:15
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: panthora
      POSTGRES_USER: panthora
      POSTGRES_DB: panthora
  search:
    image: getmeili/meilisearch:v1.4.2
    volumes:
      - search:/meili_data
    ports:
      - 7700:7700
    environment:
      #MEILI_ENV: production
      MEILI_NO_ANALYTICS: true
      MEILI_MASTER_KEY: rjzMJ0waScOlLGpEjRwy8Zx7fOlN06ZcZXcEhGvnYeFuiJuqPgpxGWv7IK5Gqw9h
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - path: ./.env
        required: true
    environment:
      DATABASE_URL: postgresql://panthora:panthora@database:5432/panthora
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_URL_INTERNAL: http://app:3000
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
      COGNITO_CLIENT_SECRET: ${COGNITO_CLIENT_SECRET}
      COGNITO_ISSUER: ${COGNITO_ISSUER}
      NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED}
      LOG_LEVEL: ${LOG_LEVEL}
      APP_BASE_URL: ${APP_BASE_URL}
      MEILI_URL: http://search:7700
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      PASSWORD_AUTH_ENABLED: ${PASSWORD_AUTH_ENABLED}
      NODE_ENV: ${NODE_ENV}

volumes:
  database:
    driver: local
  search:
    driver: local
