name: build

on:
  push:
    branches:
      - main
  pull_request:

env:
  FORCE_COLOR: 1
  SKIP_ENV_VALIDATION: true
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.43.1-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test
      - env:
          DATABASE_URL: postgresql://panthora:panthora@127.0.0.1:5432/panthora
          NEXTAUTH_SECRET: "e2e-test"
          NEXTAUTH_URL: "http://localhost:3000"
          NEXTAUTH_URL_INTERNAL: "http://localhost:3000"
          PASSWORD_AUTH_ENABLED: "true"
          VERSION: "e2e"
          DISABLE_RATE_LIMIT: true
        run: |
          docker-compose up -d search database
          pnpm --filter @panthora/app db:push
          pnpm test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: packages/app/playwright-report/
          retention-days: 7
