name: build

on:
  push:
    branches:
      - main
  pull_request:

env:
  FORCE_COLOR: 1
  SKIP_ENV_VALIDATION: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test
