name: e2e

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "packages/app/src/**"
      - "packages/app/tests/**"
      - "packages/app/package.json"

env:
  FORCE_COLOR: 1
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
      - name: Install E2E Browsers
        run: pnpm test:e2e:install
      - name: Run End-to-End Tests
        env:
          VERSION: "e2e"
          DATABASE_URL: postgresql://panthora:panthora@127.0.0.1:5432/panthora
          MEILI_URL: http://127.0.0.1:7700
          MEILI_MASTER_KEY: "e2e-test"
          NEXTAUTH_SECRET: "e2e-test"
          NEXTAUTH_URL: "http://localhost:3000"
          NEXTAUTH_URL_INTERNAL: "http://localhost:3000"
          APP_BASE_URL: "http://localhost:3000"
          PASSWORD_AUTH_ENABLED: "true"
          DISABLE_RATE_LIMIT: true
        run: |
          docker-compose up -d search database
          sleep 5
          pnpm --filter @panthora/app db:push
          pnpm test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: |
            packages/app/playwright-report/
            packages/app/test-results/
          retention-days: 7
