name: screenshots

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "packages/app/src/**"
      - "packages/app/tests/**"
      - "packages/app/package.json"

env:
  FORCE_COLOR: 1
  NEXT_TELEMETRY_DISABLED: 1
  VERSION: "e2e"
  DATABASE_URL: postgresql://panthora:panthora@127.0.0.1:5432/panthora
  MEILI_URL: http://127.0.0.1:7700
  MEILI_MASTER_KEY: "e2e-test"
  NEXTAUTH_SECRET: "e2e-test"
  NEXTAUTH_URL: "http://localhost:3000"
  NEXTAUTH_URL_INTERNAL: "http://localhost:3000"
  APP_BASE_URL: "http://localhost:3000"
  PASSWORD_AUTH_ENABLED: "true"
  DISABLE_RATE_LIMIT: true

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
      - name: Install E2E Browsers
        run: pnpm --filter @panthora/app test:e2e:install
      - name: Take Screenshots
        run: |
          docker-compose up -d search database
          sleep 5
          pnpm --filter @panthora/app db:push
          rm -rf docs/assets/screenshots
          pnpm screenshots
      - name: Commit Screenshots
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/assets/screenshots
          git commit -m "Update screenshots" || echo "No changes to commit"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
